[tool.poetry]
package-mode = false

[project]
name = "indicadores-comg"
version = "0.1.0"
description = ""
authors = [
    {name = "Codex",email = "codex@openai.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit (>=1.30,<2.0)",
    "httpx (>=0.27,<0.28)",
    "pydantic (>=2,<3)",
    "pandas (>=2,<3)",
    "plotly (>=5,<6)",
    "cachetools (>=5,<6)",
    "python-dateutil (>=2,<3)",
    "aiolimiter (>=1,<2) ; python_version >= \"3.12\" and python_version < \"4.0\""
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "^0.12.4"
pre-commit = "^4.2.0"
pytest = "^8.4.1"
pytest-asyncio = "^1.1.0"
respx = "^0.22.0"
pytest-cov = "^6.2"


[tool.ruff]
target-version = "py312"
line-length = 100
exclude = ["tests/**"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.format]
quote-style = "double"
