# Configurações Streamlit Secrets para Indicadores COMG

[arkmeds]
base_url = "https://comg.arkmeds.com"
email = "rafael.ribeiro@drumondsolucoeshospitalares.com"
password = "abc123"
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhZmFlbC5yaWJlaXJvQGRydW1vbmRzb2x1Y29lc2hvc3BpdGFsYXJlcy5jb20iLCJ1c2VyX2lkIjo0NDQsImVtYWlsIjoicmFmYWVsLnJpYmVpcm9AZHJ1bW9uZHNvbHVjb2VzaG9zcGl0YWxhcmVzLmNvbSIsImV4cCI6MTc1Mjc3MTI2Nn0.tUUgLC_QNbjfMmV3KZq-VNJD9fXOfdkaSmLIRSYy32U"

[database]
url = "sqlite:///./data/app.db"

[sync]
batch_size = 1000
max_retries = 3
