[arkmeds]
email = "rafael.ribeiro@drumondsolucoeshospitalares.com"
password = "abc123"
base_url = "https://comg.arkmeds.com"
login_path = "/rest-auth/token-auth/"
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhZmFlbC5yaWJlaXJvQGRydW1vbmRzb2x1Y29lc2hvc3BpdGFsYXJlcy5jb20iLCJ1c2VyX2lkIjo0NDQsImVtYWlsIjoicmFmYWVsLnJpYmVpcm9AZHJ1bW9uZHNvbHVjb2VzaG9zcGl0YWxhcmVzLmNvbSIsImV4cCI6MTc1MzMxNzYyMH0.2IjPf5mi9hiLorW88cOsEmmRRrudmYo9yzqwkY_yh6A"

# Configurações do Scheduler Automático
SYNC_INTERVAL_MINUTES = 15
SCHEDULER_TIMEZONE = "America/Sao_Paulo"

# Configurações de Auto-Refresh (fallback)  
AUTOREFRESH_INTERVAL_MINUTES = 30
ENABLE_AUTOREFRESH_FALLBACK = true

