ARKMEDS_EMAIL = ""
ARKMEDS_PASSWORD = ""
# ARKMEDS_TOKEN = ""
# BASE_URL = "https://<slug>.arkmeds.com"
# ARKMEDS_API_PREFIX = "/api/v5"   # mantenha vazio se BASE_URL já incluir o prefixo
# Prefixo de autenticação (default = JWT)
# ARKMEDS_AUTH_PREFIX = "JWT"
